config/routes.rb
Blog::Application.routes.draw do

  root 'web/welcome#index'

  scope :module => :web do
    resources :posts do
      scope :module => :posts do
        resources :comments
      end
    end
    resources :users
  end

  namespace :api do
    namespace :v1 do
      resources :posts, :only => [:index, :show] do
        scope :module => :posts do
          resources :comments, :only => :create
        end
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  has_many :posts, :dependent => :destroy

  validates :name, presence: true
  validates :email, uniqueness: { case_sensitive: false }

  validates_email_format_of :email
  validates :password, length: { minimum: 3 }

  has_secure_password
end

app/controllers/web/users_controller.rb
class Web::UsersController < Web::ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  add_breadcrumb :users, :users_path

  decorates_assigned :user

  def index
    @users = User.page params[:page]
  end

  def show
    add_breadcrumb @user.name, @user
  end

  def new
    add_breadcrumb :new
    @user = User.new
  end

  def edit
    add_breadcrumb @user.name, @user
    add_breadcrumb :update
  end

  def create
    @user = User.new(user_params)

    if @user.save
      f(:success)
      redirect_to @user
    else
      render action: "new"
    end
  end

  def update
    if @user.update(user_params)
      f(:success)
      redirect_to @user
    else
      render action: 'edit'
    end
  end

  def destroy
    if @user.destroy
      f(:success)
    end

    redirect_to users_url
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/web/users_helper.rb
module Web::UsersHelper
end

app/views/web/users/_form.html.haml
= simple_form_for user,
  :html => { class: "form-horizontal add-a-post" },
  :defaults => { input_html: { class: "form-control" }, wrapper_html: { class: "col-lg-10" }} do |f|
  = f.error_notification

  .form-group
    = f.input :name

  .form-group
    = f.input :email

  .form-group
    = f.input :password

  .form-group
    = f.input :password_confirmation

  .controls
    = f.button :submit, class: "btn btn-success btn-mini"

app/views/web/users/edit.html.haml
%h1= t(".edit_user")

= render "form"

= link_to users_path, class: "btn btn-default" do
  %span.icon-arrow-left
  = t(:back_btn)

app/views/web/users/index.html.haml
%h1.text-success=t(".all_users")
%table.table
  %tr
    %th= User.human_attribute_name :name
    %th= User.human_attribute_name :email

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td
        = link_to user_path(user), class: "btn btn-success" do
          = t(:show_btn)
          %span.icon-film

        = link_to edit_user_path(user), class: "btn btn-warning" do
          = t(:update_btn)
          %span.icon-edit

        = link_to user_path(user),
          :method => :delete,
          :data => { confirm: t(:confirmation) },
          :class => "btn btn-danger" do
          = t(:delete_btn)
          %span.icon-remove

= paginate @users

= link_to new_user_path, class: "btn btn-default" do
  = t(:create_btn)
  %span.icon-leaf

app/views/web/users/new.html.haml
%h1=t(".new_user")

= render 'form'

= link_to users_path, class: "btn btn-default" do
  %span.icon-arrow-left
  = t(:back_btn)

app/views/web/users/show.html.haml
%p
  %strong= "#{User.human_attribute_name :name}:"
  = user.blockquotes_name

%p
  %strong= "#{User.human_attribute_name :email}:"
  = user.blockquotes_email

%h2= "#{Post.model_name.human count: 0}:"

= render user.posts

.footer-buttons
  = link_to users_path, class: "btn btn-default" do
    %span.icon-arrow-left
    = t(:back_btn)
  |
  = link_to edit_user_path(user), class: "btn btn-default" do
    %span.icon-edit
    = t(:update_btn)