config/routes.rb
Blog::Application.routes.draw do

  root 'web/welcome#index'

  scope :module => :web do
    resources :posts do
      scope :module => :posts do
        resources :comments
      end
    end
    resources :users
  end

  namespace :api do
    namespace :v1 do
      resources :posts, :only => [:index, :show] do
        scope :module => :posts do
          resources :comments, :only => :create
        end
      end
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  belongs_to :user
  accepts_nested_attributes_for :comments, allow_destroy: true, :reject_if => :all_blank

  validates :title, presence: true, length: { minimum: 3 }

  mount_uploader :picture, PictureUploader

  state_machine :initial => :unpublished do
    state :unpublished
    state :published

    event :publish do
      transition :unpublished => :published
    end
  end

  include PostRepository
end

app/models/post/comment.rb
class Post::Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :commenter, class_name: "User"

  has_ancestry
end

app/controllers/api/v1/posts/application_controller.rb
class Api::V1::Posts::ApplicationController < Api::ApplicationController
  helper_method :resource_post

  private
    def resource_post
      @resource_post ||= Post.find(params[:post_id])
    end
end

app/controllers/api/v1/posts/comments_controller.rb
class Api::V1::Posts::CommentsController < Api::V1::Posts::ApplicationController
  def create
    comment = resource_post.comments.build(comment_params)
    comment.save
    # debugger
    # respond_with(comment, :location => nil, :status => :created)
    render nothing: true, status: :created
  end

  private
    def comment_params
      params[:post_comment].permit(:body, :parent_id, :commenter_id)
    end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::ApplicationController
  def index
    @posts = Post.published.ransack(params[:q])
    @posts = @posts.result(distinct: true)
    @posts = @posts.page params[:page]

    respond_with @posts
  end

  def show
    @post = Post.find(params[:id])

    respond_with @post
  end
end

app/controllers/post/comments_controller.rb
class Post::CommentsController < ApplicationController
  http_basic_authenticate_with name: "user", password: "user", only: :destroy unless Rails.env.test?

  def new_child
    post = Post.find(params[:post_id])
    @comment = post.comments.build(parent_id: params[:id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:post_comment].permit(:commenter, :body, :parent_id))
    flash[:notice] = "Comment was successfully created." if @comment

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "user", password: "user", except: [:index, :show] unless Rails.env.test?

  add_breadcrumb "/", :root_path
  add_breadcrumb :posts, :posts_path

  def index
    @posts = Post.page params[:page]
  end

  def new
    add_breadcrumb :new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
    add_breadcrumb @post.title, @post
    add_breadcrumb :update
  end

  def create
    @post = Post.new(get_post_params)
    if @post.save
      flash[:notice] = "Post was successfully created."
      redirect_to @post
    else
      render "new"
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(get_post_params)
      redirect_to @post
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
    add_breadcrumb @post.title, @post
    flash[:notice] = "Show post with id: #{@post.id}"
  end

  private
  def get_post_params
    params.require(:post).permit(:title, :text, :picture)
  end
end

app/controllers/web/posts/application_controller.rb
class Web::Posts::ApplicationController < Web::ApplicationController
  helper_method :resource_post

  before_filter do
    add_breadcrumb :posts, :posts_path
    add_breadcrumb resource_post.title, resource_post
  end

  private
  def resource_post
    @resource_post ||= Post.find(params[:post_id])
  end
end

app/controllers/web/posts/comments_controller.rb
class Web::Posts::CommentsController < Web::Posts::ApplicationController
  http_basic_authenticate_with name: configus.user.name, password: configus.user.password, :only => :destroy unless Rails.env.test?

  def create
    @post = resource_post
    @comment = @post.comments.create(comment_params)
    f(:success) if @comment

    redirect_to post_path(@post)
  end

  def destroy
    @post = resource_post
    @comment = @post.comments.find(params[:id])
    if @comment.destroy
      f(:success)
    end
    redirect_to post_path(@post)
  end

  def comment_params
    params[:post_comment].permit(:body, :parent_id, :commenter_id)
  end
end

app/controllers/web/posts_controller.rb
class Web::PostsController < Web::ApplicationController
  http_basic_authenticate_with name: configus.user.name, password: configus.user.password, except: [:index, :show] unless Rails.env.test?

  add_breadcrumb :posts, :posts_path

  decorates_assigned :post

  def index
    @q = Post.published.ransack(params[:q])
    @posts = @q.result(distinct: true)
    @posts = @posts.page params[:page]
  end

  def new
    add_breadcrumb :new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
    add_breadcrumb @post.title, @post
    add_breadcrumb :update
  end

  def create
    @post = Post.new(get_post_all_params)

    if @post.save
      f(:success)
      redirect_to @post
    else
      render "new"
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(get_post_all_params)
      f(:success)
      redirect_to @post
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      f(:success)
    end

    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
    add_breadcrumb @post.title, @post
  end

  private
  def get_post_all_params
    params.require(:post).permit(post_params, :comments_attributes => comment_params)
  end

  def post_params
    [:title, :text, :picture, :state_event, :user_id]
  end

  def comment_params
    [:id, :body, :post_id, :commenter_id]
  end
end

app/helpers/web/posts/comments_helper.rb
module Web::Posts::CommentsHelper
  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(partial: "web/posts/comments/comment", object: comment) +
        content_tag(:div, nested_comments(sub_comments), class: "nested-comments")
    end.join.html_safe
  end
end

app/helpers/web/posts_helper.rb
module Web::PostsHelper
end

app/views/web/posts/_filter.html.haml
.search-form
  = search_form_for search do |f|
    = f.label :title_cont
    = f.text_field :title_cont
    = f.label :text_start
    = f.text_field :text_start

    .form-group
      = f.submit class: "btn btn-info btn-mini"

app/views/web/posts/_form.html.haml
= simple_form_for post,
  :html => { class: "form-horizontal add-a-post" },
  :defaults => { input_html: { class: "form-control" }, wrapper_html: { class: "col-lg-10" }} do |f|
  = f.error_notification

  .form-group
    = f.input :title

  .form-group
    = f.input :text, :as => :text

  .form-group
    = f.input :picture

  .form-group
    = f.input :state_event, :as => :state_event

  .form-group
    = f.association :user

  .form-group
    %h3= "#{Post::Comment.model_name.human count: 0}:"
    #comments
      = f.simple_fields_for :comments do |comment|
        = render "web/posts/comments/comment_fields", :f => comment
      .links
        = link_to_add_association t(:add_btn), f, :comments,
          :partial => "web/posts/comments/comment_fields",
          :class => "btn btn-primary btn-mini"

  .controls
    = f.button :submit, class: "btn btn-success btn-mini"

app/views/web/posts/_post.html.haml
.post
  %p
    %strong= "#{Post.human_attribute_name :title}:"
    = post.title
    %br
    %strong= "#{Post.human_attribute_name :text}:"
    = post.text

  %p
    = link_to post_path(post),
      :method => :delete,
      :data => { confirm: t(:confirmation) },
      :class => "btn btn-danger btn-mini" do
      = t(:delete_btn)
      %span.icon-remove

    = link_to edit_post_path(post),
      :class => "btn btn-warning btn-mini" do
      = t(:update_btn)
      %span.icon-edit

app/views/web/posts/edit.html.haml
%h1= t(".edit_post")

= render "form"

= link_to posts_path, class: "btn btn-default" do
  %span.icon-arrow-left
  = t(:back_btn)

app/views/web/posts/index.html.haml
%h1.text-success=t(".all_posts")

= render partial: "filter", locals: { search: @q }

%table.table
  %tr
    %th= Post.human_attribute_name :title
    %th= Post.human_attribute_name :text

  - @posts.each do |post|
    %tr
      %td= post.title
      %td= post.text
      %td
        = link_to post_path(post), class: "btn btn-success" do
          = t(:show_btn)
          %span.icon-film

        = link_to edit_post_path(post), class: "btn btn-warning" do
          = t(:update_btn)
          %span.icon-edit

        = link_to post_path(post),
          :method => :delete,
          :data => { confirm: t(:confirmation) },
          :class => "btn btn-danger" do
          = t(:delete_btn)
          %span.icon-remove

= paginate @posts

= link_to new_post_path, class: "btn btn-default" do
  = t(:create_btn)
  %span.icon-leaf

app/views/web/posts/new.html.haml
%h1=t(".new_post")

= render "form"

= link_to posts_path, class: "btn btn-default" do
  %span.icon-arrow-left
    = t(:back_btn)

app/views/web/posts/show.html.haml
%p
  %strong= "#{Post.human_attribute_name :title}:"
  = post.title
  |
  = post.created_at

%p
  %strong= "#{Post.human_attribute_name :text}:"
  = post.text

%p
  %strong= "#{Post.human_attribute_name :picture}:"
  = image_tag post.picture, class: "post-image"

%h2= "#{Post::Comment.model_name.human count: 0}:"

%button.btn{ type: "button", data: { toggle: "collapse", target: "#demo" }}
  %span.icon-comment
  = t(".add_comment")
.collapse_in.collapse#demo
  = render "web/posts/comments/form"

= nested_comments post.comments.arrange(:order => :created_at)

= render partial: "web/shared/modal_form", locals: { title: t(".add_comment"), body: "web/posts/comments/form" }

.footer-buttons
  = link_to posts_path, class: "btn btn-default" do
    %span.icon-arrow-left
    = t(:back_btn)
  |
  = link_to edit_post_path(post), class: "btn btn-default" do
    %span.icon-edit
    = t(:update_btn)